name: Run Build & Deploy Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run load script
        run: curl --request GET \
             --url 'https://api-football-v1.p.rapidapi.com/v3/fixtures?league=71&season=2024' \
             --header 'x-rapidapi-host:api-football-v1.p.rapidapi.com' \
             --header 'x-rapidapi-key:${{ secrets.API_TOKEN }}' > fixtures.json
      - name: Copy fixtures
        run: cp ./fixtures.json ./src/assets/fixtures.json
      - name: Install npm packages
        run: npm install
      - name: Run build script
        run: npm run build:prod
      - name: Deploy application
        run: npm run deploy
